### PR TITLE
Update base-images.md

### PR DESCRIPTION
**Pull request by pankajroark**

### CODE REVIEW

**Review by philipkiely-baseten — CHANGES_REQUESTED** [review]
Let me do a quick copyedit of this page. Will do right now and unblock before merging.

**Review by philipkiely-baseten — APPROVED** [review]
@pankajroark I tried my best to clarify and shorten the docs. Please let me know if I left out any key details.

I also re-organized this as a "contributor" doc because it only seems relevant to people contributing to Truss, not everyday users. If that's incorrect, I'll put it back with the main docs.

**Comment by philipkiely-baseten** [comment]
@pankajroark is this good to merge?

**Comment by bolasim** [comment]
@philipkiely-baseten this looks good. Can you just resolve the conflicts and we'll merge it?

**Comment by philipkiely-baseten** [comment]
Cool, rebased and merged!

**Pull request merged**
